"""
【執筆メモStart】
python manage.py makemigrationsで自動生成されたままの状態です。
【執筆メモEnd】
"""
# Generated by Django 4.1.2 on 2022-10-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hello",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("world", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "hello",
            },
        ),
    ]
