version: 0.2
env:
  variables:
    docker_token: 2d576e6a-c045-4ad9-8338-64c7e21f2188
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo $docker_token | docker login -u opentoneitou --password-stdin
      - REPOSITORY_URI_BACKEND=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECS_BACKEND
      - REPOSITORY_URI_FRONTEND=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECS_FRONTEND
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - docker build -t $REPOSITORY_URI_BACKEND:latest backend --build-arg environment_name=$ENVIRONMENT_NAME
      - docker tag $REPOSITORY_URI_BACKEND:latest $REPOSITORY_URI_BACKEND:$IMAGE_TAG
      - docker build -t $REPOSITORY_URI_FRONTEND:latest frontend
      - docker tag $REPOSITORY_URI_FRONTEND:latest $REPOSITORY_URI_FRONTEND:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY_URI_BACKEND:latest
      - docker push $REPOSITORY_URI_BACKEND:$IMAGE_TAG
      - docker push $REPOSITORY_URI_FRONTEND:latest
      - docker push $REPOSITORY_URI_FRONTEND:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"},{"name":"%s","imageUri":"%s"}]' $ECS_BACKEND $REPOSITORY_URI_BACKEND:$IMAGE_TAG $ECS_FRONTEND $REPOSITORY_URI_FRONTEND:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
