"""
【執筆メモStart】
python manage.py makemigrationsで自動生成されたままの状態です。
【執筆メモEnd】
"""
# Generated by Django 4.1.2 on 2022-10-17 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="商品名")),
            ],
            options={
                "verbose_name": "商品",
                "db_table": "product_back",
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="販売価格")),
                ("start_date", models.DateField(verbose_name="開始日")),
                ("end_date", models.DateField(verbose_name="終了日")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_product",
                        to="product.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "価格",
                "db_table": "price",
            },
        ),
    ]
