/*
【執筆メモStart】
yarn create next-appで自動生成されたままの状態です。
【執筆メモEnd】
*/
export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
