# Generated by Django 4.1.2 on 2023-02-01 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalesFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=100, verbose_name="ファイル名")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "未処理"), (2, "処理済")], default=1, verbose_name="状態"
                    ),
                ),
            ],
            options={
                "verbose_name": "売上ファイル",
                "db_table": "sales_file",
            },
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sales_date", models.DateField(verbose_name="売上日付")),
                ("price", models.IntegerField(verbose_name="価格")),
                (
                    "import_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sales.salesfile",
                        verbose_name="売上ファイルID",
                    ),
                ),
            ],
            options={
                "verbose_name": "売上",
                "db_table": "sales",
            },
        ),
    ]
